server:
  port: 8084

spring:
  config:
    import: optional:gitignore/hidden.properties

  rabbitmq:
    host: ${rabbit.host:localhost}
    port: ${rabbit.port:5672}
    username: ${rabbit.username:guest}
    password: ${rabbit.password:guest}

  mail:
    host: smtp.mail.ru
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

remote-services:
  user-service:
    host: user-service
    port: 8081
    url: http://${remote-services.user-service.host}:${remote-services.user-service.port}
