server:
  port: 8084

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: iNQU1SITOR
    password: Utermybest1

  mail:
    host: smtp.mail.ru
    port: 587
    username: sankevich2003@mail.ru
    password: BE571z83rLcYjKkX98Dr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true