server:
  port: 8084

spring:
  config:
    import: optional:gitignore/hidden.properties

  rabbitmq:
    host: localhost
    port: 5672
    username: iNQU1SITOR
    password: Utermybest1

  mail:
    host: smtp.mail.ru
    port: 587
    username: sankevich2003@mail.ru
    password: BE571z83rLcYjKkX98Dr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

remote-services:
  user-service:
    host: user-service
    port: 8081
    url: http://${remote-services.user-service.host}:${remote-services.user-service.port}
