POST localhost:9000/oauth2/token
Authorization: Basic intexsoft intexsoft
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&redirect_uri=http://127.0.0.1:9090/authorized&code=b_zs6TWBZ4TYgfrzw3qWZMbVtCXUK1dlTfc1MZZc6cXqTgn3jCZdcnWIuLrblw4PrmkbnsMHCOR0wXYay79yrPTdAIGdtavnDwYxGp8MIUtoyG4MJ25gwnKEmGxaWXgR
###