server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

logging:
  level:
    src.main.java.me.inqu1sitor.clients: DEBUG
