server:
  port: 8080

spring:
  redis:
    host: ${redis.host:localhost}
    port: ${redis.port:6379}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

logging:
  level:
    src.main.java.me.inqu1sitor.clients: DEBUG

remote-services:
  user-service:
    host: user-service
    port: 8081
    url: http://${remote-services.user-service.host}:${remote-services.user-service.port}

  auth-service:
    host: auth-service
    port: 9000
    url: http://${remote-services.auth-service.host}:${remote-services.auth-service.port}
