server:
  port: 9000

spring:
  redis:
    host: localhost
    port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: iNQU1SITOR
    password: Utermybest1

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Utermybest1
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    default-schema: auth_service

  jpa:
    properties:
      hibernate:
        default_schema: auth_service
    open-in-view: false

    hibernate:
      ddl-auto: validate

    generate-ddl: false

logging:
  level:
    src.main.java.me.inqu1sitor.authservice.clients: DEBUG

remote-services:
  user-service:
    host: user-service
    port: 8081
    url: http://${remote-services.user-service.host}:${remote-services.user-service.port}