server:
  port: 9000

spring:
  config:
    import: optional:gitignore/hidden.properties

  redis:
    host: ${redis.host:localhost}
    port: ${redis.port:6379}

  rabbitmq:
    host: ${rabbit.host:localhost}
    port: ${rabbit.port:5672}
    username: ${rabbit.username:guest}
    password: ${rabbit.password:guest}

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${jwk-set-uri}

  datasource:
    url: ${datasource.url:jdbc:postgresql://localhost:5432/postgres}
    username: ${datasource.username:}
    password: ${datasource.password:}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    default-schema: auth_service

  jpa:
    properties:
      hibernate:
        default_schema: auth_service
    open-in-view: false

    hibernate:
      ddl-auto: validate

    generate-ddl: false

logging:
  level:
    src.main.java.me.inqu1sitor.authservice.clients: DEBUG

remote-services:
  user-service:
    host: user-service
    port: 8081
    url: http://${remote-services.user-service.host}:${remote-services.user-service.port}