server:
  port: 9000



spring:
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
      password:

  rabbitmq:
    host: localhost
    port: 5672
    username: iNQU1SITOR
    password: Utermybest1

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Utermybest1
    driver-class-name: org.postgresql.Driver

  test:
    database:
      replace: none

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    default-schema: auth_service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: auth_service
        format_sql: true

    hibernate:
      ddl-auto: validate

    show-sql: true
    generate-ddl: false

logging:
  level:
    me.inqu1sitor.authservice.clients: DEBUG
