server:
  port: 8081

spring:
  config:
    import: optional:gitignore/hidden.properties

  rabbitmq:
    host: ${rabbit.host:localhost}
    port: ${rabbit.port:5672}
    username: ${rabbit.username:guest}
    password: ${rabbit.password:guest}

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${jwk-set-uri}

  datasource:
    url: ${datasource.url:jdbc:postgresql://localhost:5432/postgres}
    username: ${datasource.username:}
    password: ${datasource.password:}
    driver-class-name: org.postgresql.Driver

  test:
    database:
      replace: none

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    default-schema: user_service

  jpa:
    properties:
      hibernate:
        default_schema: user_service

    hibernate:
      ddl-auto: validate

    generate-ddl: false
